//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InterventionMedicaleDTO } from './intervention.dto';
import { CoronarographieDTO } from './coronarographie.dto';
import { TraitementDTO } from './traitement.dto';
import { MaterielDTO } from './materiel.dto';
import { ProcedureDTO } from './procedure.dto';

export class AngioplastieDTO extends InterventionMedicaleDTO
{
 constructor() {
   super();
  }
 public PADiastolique: number;
 public PASystolique: number;
 public FreqCardique: number;
 public AbordArterielPrincipal: string;
 public AnticoagulantIV: string;
 public AnticaogulantIVQte: number;
 public RisordanQte: number;
 public LoxenQte: number;
 public AntiGIIBIIIQte: number;
 public Coronarographie: CoronarographieDTO;
 public Traitements: TraitementDTO[];
 public Materiels: MaterielDTO[];
 public Procedures: ProcedureDTO[];
}
