//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InterventionMedicaleDTO } from './intervention.dto';
import { CoronarographieDTO } from './coronarographie.dto';
import { TraitementDTO } from './traitement.dto';
import { MaterielDTO } from './materiel.dto';
import { ProcedureDTO } from './procedure.dto';
import { CardiologueDTO } from './cardiologue.dto';

export class AngioplastieDTO extends InterventionMedicaleDTO {
  constructor() {
    super();

    this.cardiologue = new CardiologueDTO();
    this.traitements = new Array<TraitementDTO>();
    this.materiels = new Array<MaterielDTO>();
    this.procedures = new Array<ProcedureDTO>();
  }
  public pADiastolique: number;
  public pASystolique: number;
  public freqCardique: number;
  public abordArterielPrincipal: string;
  public anticoagulantIV: string;
  public anticaogulantIVQte: number;
  public risordanQte: number;
  public loxenQte: number;
  public antiGIIBIIIQte: number;
  public coronarographie: CoronarographieDTO;
  public traitements: TraitementDTO[];
  public materiels: MaterielDTO[];
  public procedures: ProcedureDTO[];
}
