//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { MaterielDTO } from './materiel.dto';
import { ProcedureDTO } from './procedure.dto';

export class BallonDTO extends MaterielDTO
{
 public Type: string;
 public Longueur: number;
 public Diametre: number;
 public Phase: string;
 public ProcedureId: number;
 public Procedure: ProcedureDTO;
}
