//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InterventionMedicaleDTO } from './intervention.dto';

export class BiologieDTO
{
 public Id: number;
 public Creatinine: number;
 public CLCreatinine: number;
 public IRC: string;
 public Hemoglobine: number;
 public INR: number;
 public PicTroponine: number;
 public InterventionMedicale: InterventionMedicaleDTO;
}
