//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class CardiologueDTO
{
 public CIN: number;
 public Nom: string;
 public Prenom: string;
 public Qualification: string;
 public Username: string;
 public Password: string;
 public Role: string;
}
