//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CoronarographieDTO } from './coronarographie.dto';

export class ContrasteDosimetrieDTO
{
 public Id: number;
 public TypePDC: string;
 public QtePDC: number;
 public QtePDS: number;
 public NombreImages: number;
 public Coronarographie: CoronarographieDTO;
}
