//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InterventionMedicaleDTO } from './intervention.dto';
import { FacteursRisqueAntecedantsDTO } from './facteurs.dto';
import { AngioplastieDTO } from './angioplastie.dto';
import { ContrasteDosimetrieDTO } from './contraste-dosimetrie.dto';
import { LesionDTO } from './lesion.dto';
import { CardiologueDTO } from './cardiologue.dto';

export class CoronarographieDTO extends InterventionMedicaleDTO {

  /**
   *
   */
  constructor() {
    super();

    this.Cardiologue = new CardiologueDTO();
    this.FacteursRisqueAntecedants = new FacteursRisqueAntecedantsDTO();
    this.Angioplastie = new AngioplastieDTO();
    this.ContrasteDosimetrie = new ContrasteDosimetrieDTO();
    this.Lesions = new Array<LesionDTO>();
  }

  public Voie: string;
  public Statut: string;
  public MotifPrinc: string;
  public AutreMotif: string;
  public FeVG: number;
  public FacteursRisqueAntecedants: FacteursRisqueAntecedantsDTO;
  public Angioplastie: AngioplastieDTO;
  public ContrasteDosimetrie: ContrasteDosimetrieDTO;
  public Lesions: LesionDTO[];
}
