//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InterventionMedicaleDTO } from './intervention.dto';
import { FacteursRisqueAntecedantsDTO } from './facteurs.dto';
import { AngioplastieDTO } from './angioplastie.dto';
import { ContrasteDosimetrieDTO } from './contraste-dosimetrie.dto';
import { LesionDTO } from './lesion.dto';

export class CoronarographieDTO extends InterventionMedicaleDTO
{
 public Voie: string;
 public Statut: string;
 public MotifPrinc: string;
 public AutreMotif: string;
 public FeVG: number;
 public FacteursRisqueAntecedantsId: number;
 public FacteursRisqueAntecedants: FacteursRisqueAntecedantsDTO;
 public AngioplastieId: number;
 public Angioplastie: AngioplastieDTO;
 public ContrasteDosimetrieId: number;
 public ContrasteDosimetrie: ContrasteDosimetrieDTO;
 public Lesions: LesionDTO[];
}
