//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { InterventionMedicaleDTO } from './intervention.dto';
import { FacteursRisqueAntecedantsDTO } from './facteurs.dto';
import { AngioplastieDTO } from './angioplastie.dto';
import { ContrasteDosimetrieDTO } from './contraste-dosimetrie.dto';
import { LesionDTO } from './lesion.dto';
import { CardiologueDTO } from './cardiologue.dto';
import { BiologieDTO } from './biologie.dto';

export class CoronarographieDTO extends InterventionMedicaleDTO {

  /**
   *
   */
  constructor() {
    super();

    this.cardiologue = new CardiologueDTO();
    this.facteursRisqueAntecedants = new FacteursRisqueAntecedantsDTO();
    this.angioplastie = new AngioplastieDTO();
    this.contrasteDosimetrie = new ContrasteDosimetrieDTO();
    this.lesions = new Array<LesionDTO>();
    this.biologie = new BiologieDTO();
  }

  public voie: string;
  public statut: string;
  public motifPrinc: string;
  public autreMotif: string;
  public feVG: number;
  public facteursRisqueAntecedants: FacteursRisqueAntecedantsDTO;
  public angioplastie: AngioplastieDTO;
  public contrasteDosimetrie: ContrasteDosimetrieDTO;
  public lesions: LesionDTO[];
}
