//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CoronarographieDTO } from './coronarographie.dto';

export class FacteursRisqueAntecedantsDTO
{
 public Id: number;
 public Taille: number;
 public Poids: number;
 public IMC: number;
 public Obesite: string;
 public HTA: boolean;
 public Diabete: boolean;
 public TypeDiabete: string;
 public AncDiabete: number;
 public Tabac: boolean;
 public Dysplidemie: boolean;
 public AIT: boolean;
 public AVCIsh: boolean;
 public AVCHem: boolean;
 public ATCDIDM: boolean;
 public ATCDATL: boolean;
 public ATCDPAC: boolean;
 public Coronarographie: CoronarographieDTO;
}
