//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CardiologueDTO } from './cardiologue.dto';
import { PatientDTO } from './patient.dto';
import { BiologieDTO } from './biologie.dto';

export abstract class InterventionMedicaleDTO {

  /**
   *
   */
  constructor() {
    this.cardiologue = new CardiologueDTO();
  }
  public id: number;
  public nom: string;
  public numero: number;
  public date: any;
  public estUrgente: boolean;
  public cin: number;
  public cardiologue: CardiologueDTO;
  public patientId: number;
  public patient: PatientDTO;
  public biologieId: number;
  public biologie: BiologieDTO;
}
