//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { CardiologueDTO } from './cardiologue.dto';
import { PatientDTO } from './patient.dto';
import { BiologieDTO } from './biologie.dto';

export abstract class InterventionMedicaleDTO
{
 public Id: number;
 public Nom: string;
 public Numero: string;
 public Date: any;
 public estUrgente: boolean;
 public CIN: number;
 public Cardiologue: CardiologueDTO;
 public PatientId: number;
 public Patient: PatientDTO;
 public BiologieId: number;
 public Biologie: BiologieDTO;
}
