//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { AngioplastieDTO } from './angioplastie.dto';

export class MaterielDTO {
  public Id: number;
  public TailleDesilet: number;
  public CGReseauG: string;
  public CGReseauD: string;
  public Pontage: string;
  public Angioplastie: AngioplastieDTO;
}
