//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { AngioplastieDTO } from './angioplastie.dto';
import { StentDTO } from './stent.dto';
import { BallonDTO } from './ballon.dto';
import { GuideDTO } from './guide.dto';

export class ProcedureDTO
{
 public Id: number;
 public Technique: string;
 public TIMIFinal: number;
 public Resultat: string;
 public AngioplastieId: number;
 public Angioplastie: AngioplastieDTO;
 public Stents: StentDTO[];
 public Ballons: BallonDTO[];
 public Guides: GuideDTO[];
}
