//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { AngioplastieDTO } from './angioplastie.dto';

export class TraitementDTO
{
 public Id: number;
 public Nom: string;
 public Date: any;
 public Posologie: number;
 public AngioplastieId: number;
 public Angioplastie: AngioplastieDTO;
}
